dev-sec/ssh-baseline

default/serverspec/ssh_spec.rb
When running the current version of tests for our crypto algos and a spec fails, we get an output similar to this:
2) check sshd_config File "/etc/ssh/sshd_config" content should valid cipher
Failure/Error: should valid_cipher
expected "..." to valid cipher
This is not very helpful, since it doesn't tell us what it really expects (e.g. a list of valid ciphers). Best case scenario: you only have to look into the spec file, worst case: your spec has some other error (like OS-detection) and it starts to get really messy.
This implementation fixes this issue. It is not as elegant as the current one, but prints very descriptive errors:
2) check ssh_config File "/etc/ssh/ssh_config" content should match /^Ciphers aes256-ctr,aes192-ctr,aes128-ctr$/
=> Descriptive spec

default/serverspec/ssh_spec.rb
we originally removed GCM from the cipher chain due to vulnerabilities in OpenSSH. We are adding it back, since any sensible implementation will have had enough time to fix or backport. On top of that, GCM is generally a preferred algorithm. Let's get it back now.
=> feature: add back gcm

default/serverspec/ssh_spec.rb
=> feature: UsePrivilegeSeparation = sandbox for ssh >= 5.9

default.yml, playbooks/default.yml
This file is needed as a wrapper to run the ansible-playbooks on the test-hosts.
=> Add Ansible support

ansible_1.9, ansible_latest
The two suite names for the inspec tests refer to different Ansible
versions to test, but the inspec tests themselves should be the same for
both versions of Ansible. Therefore let's use symlinks so that the
inspec runner finds "default" when it searches for:
* ansible_latest
* ansible_1.9
Voila.
=> Symlinks real suite names to "default"

Gemfile
pin rake dependency, since newer versions require rack which requires Ruby version >= 2.2.2.
=> pin rake version

libraries/ssh_crypto.rb
In the latest version of inspec (0.30.0) ubuntu nodes are classified as being part of the Debian family (and not in a family of its own).
This pull requests fixes this shortcoming (tested on 12.04, 14.04, 16.04)
=> Fixing inspec tests for ubuntu hosts

controls/sshd_spec.rb
This commit introduces tests for the configuration of Banner
and DebianBanner in preparation for upcoming implementation PRs
for puppet, chef and ansible.
=> Test server config for Banner and DebianBanner

controls/sshd_spec.rb
as PAM should be enabled per default on the most distros:
- https://github.com/dev-sec/chef-ssh-hardening/issues/96
- https://github.com/dev-sec/ansible-ssh-hardening/issues/23
- https://github.com/dev-sec/puppet-ssh-hardening/issues/53
=> Remove the PAM deactivation enforcement

.gitignore
This is a minor fix, but InSpec creates an `inspec.lock` file in the profile directory when the profile is executed and it subsequently shows up in untraced files.
=> Ignore inspec.lock file

controls/ssh_spec.rb, controls/sshd_spec.rb
Fixes bug introduced by #82 
```
×  File /etc/ssh/ssh_config
undefined method `darwin' for Operating System Detection:#<Class:0x007fe3711f3680>
```
=> Fix check for os.darwin

libraries/ssh_crypto.rb
Opensuse 42.1 is running openssh 6.6
=> Proper tests for Opensuse leap 42.1

.travis.yml, Gemfile, Rakefile, libraries/ssh_crypto.rb
Chef 13 is also using ruby 2.4.1 in the omnibus packages
=> CI: update to ruby 2.4.1 and rubocop 0.49

controls/sshd_spec.rb
While this cookbook isn't specific (and shouldn't be specific) to CIS Benchmarks, it's helpful as a
baseline to set the default behaviors to the recommended value. Folks can override to 600 if needed
in chef-ssh-hardening cookbook.
=> Modified the client_alive_interval default to suggested value

controls/sshd_spec.rb
since sshd_config dose not have the path method, sshd-47 reports the false-negative on non Debian platform.
=> Fix bogus success of sshd-47 on non Debian

controls/sshd_spec.rb
With command it fails for whatever reason, with bash resource
it works just fine:
```bash
×  sshd-48: Server: DH primes (1 failed)
✔  Command: `test $(awk '$5 < 2047 && $5 ~ /^[0-9]+$/ { print $5 }'
/etc/ssh/moduli | uniq | wc -c) -eq 0` exit_status should eq 0
✔  Command: `test $(awk '$5 < 2047 && $5 ~ /^[0-9]+$/ { print $5 }'
/etc/ssh/moduli | uniq | wc -c) -eq 0` stdout should eq ""
×  Command: `test $(awk '$5 < 2047 && $5 ~ /^[0-9]+$/ { print $5 }'
/etc/ssh/moduli | uniq | wc -c) -eq 0` stderr should eq ""
expected: ""
got: "awk: cmd. line:1: fatal: cannot open file
`/etc/ssh/moduli' for reading (Permission denied)\n"
(compared using ==)
Diff:
@@ -1 +1,2 @@
+awk: cmd. line:1: fatal: cannot open file `/etc/ssh/moduli' for
reading (Permission denied)
```
Signed-off-by: Artem Sidorenko …
=> Avoid failing on EL 6 family and OpenSuse Leap 42

libraries/ssh_crypto.rb
Ubuntu 18.04 deprecated the option.
=> Add separate PrivilegeSeparation check for Ubuntu 1804

libraries/ssh_crypto.rb
Amazon Linux still has it with OpenSSH 7.4
=> Fixup of UsePrivilegeSeparation deprecation for Amazon

libraries/ssh_crypto.rb
This pull request includes #119 plus additional fixes for all other OS version detection.
=> Fix os detection

controls/ssh_spec.rb
UseRoaming was deprecated in OpenSSH 7.2, see this commit:
https://github.com/openssh/openssh-portable/commit/a306863831c57ec5fad918687cc5d289ee8e2635
This PR adds a condition so the control checks only on
older version.
Fixes #121
=> UseRoaming is deprecated, only check on older versions

controls/sshd_spec.rb
without-password is already allowed, and prohibit-password is just an alias
supposed to make it clearer what it does.
=> Allow prohibit-password as PermitRootLogin value

.rubocop.yml, CHANGELOG.md, Gemfile, Rakefile, inspec.yml, libraries/ssh_crypto.rb
Switched to inspec check without CLI, this will allow checking the profile with inspec 4 without having to auto accept the license.
I updated the Rakefile to only load the changelog task when it is targetted.
I had to specify the repo user and project in the config of the changelog task, otherwise, I was getting this exception:
```
Octokit::InvalidRepository: "/" is invalid as a repository identifier. Use the user/repo (String) format
```
=> Bump version to 2.4.1 and switch to inspec 3 for check

libraries/ssh_crypto.rb
https://www.openssh.com/txt/release-7.5
=> Debian 10 has Openssh 7.9 with deperecated UsePrivilegeSeparation

controls/sshd_spec.rb, inspec.yml
Add reference and more detailed description of this configuration option
(taken from CIS benchmark document).
Allow ability to override the default of 2, in some instances this can be too
aggressive causing lockouts to users with multiple keys loaded in the ssh agent.
=> Issue 137 - MaxAuthTries Parameter.

controls/sshd_spec.rb
=> Issue 139 - Use cmp instead of be matcher to allow string matching 

controls/sshd_spec.rb, inspec.yml
This solves an unwanted sideeffect of #138 where passing an attributes.yml to inspec that doesn't contain max_auth_tries it breaks the test. This change solves that, you can now still override the attribute if you need more or less tries but you can now pass attributes again without explicitly repeating the default value (2). Also refactors to a more clear attribute name.
=> Move atribute to spec as local var

.rubocop.yml, libraries/ssh_crypto.rb
Closes #145 
I have not tested these HMACs Oracle Linux 6.5, however according to their documentation there is no package change for OpenSSH from their upstream.
=> Use SHA2 HMACs in OpenSSH for RHEL family 6.5+

controls/ssh_spec.rb, controls/sshd_spec.rb
Add the option to choose the owner of configurations files and their locations.
=> In a container, sshd should not run as root

controls/sshd_spec.rb
Sometimes, port 22 is already in use or is forbidden (non root user running sshd).
=> sshd custom port

libraries/ssh_crypto.rb
Do the attributes work in libraries ? Are they called the way I did ?
=> custom path for hostkeys

controls/sshd_spec.rb
There can be multiple ListenAddress (for instance ipv6 and ipv4 failover).
Does the `exist` matcher work for sshd_config ?
=> ListenAddress should exist

libraries/ssh_crypto.rb
as per https://github.com/dev-sec/ssh-baseline/issues/144 
added URLs for future package version quick reference & check; can be removed though.
=> OpenSSH 8.0 KEXs support

controls/sshd_spec.rb
Sometimes, ssh host keys must be in a different path. In a mountpoint in a clustered environment for instance.
=> ssh host keys in a specific directory

libraries/ssh_crypto.rb
these Linuxes come with OpenSSH 8 and should use the matching Kex
=> use correct kex for RedHat/CentOS/Oracle Linux 8

controls/sshd_spec.rb
RedHat introduces a CRYPTO_POLICY in RHEL8. This needs to be configured
separately, or it will override sshd_config settings for Cipher, MAC and
Kex.
see: https://access.redhat.com/solutions/4410591
=> add control for CRYPTO_POLICY on RedHat

controls/ssh_spec.rb, controls/sshd_spec.rb
since fedora uses different version scheme it was not covered by previous
check. Also add checks for ssh client, to see if we successfully
override CRYPTO_POLICY there
Signed-off-by: Martin Schurz <Martin.Schurz@t-systems.com>
=> rework CRYPTO_POLICY check to work with fedora

libraries/ssh_crypto.rb
OpenSSH 8.5 was released on 2021-03-03 and was officially made available for Arch Linux on 2021-03-04 17:09 UTC. The previous key exchange method `sntrup4591761x25519-sha512@tinyssh.org` is replaced with `sntrup761x25519-sha512@openssh.com` in this release. Consequently, the `ssh_crypto.rb` library has to be updated.
=> Added OpenSSH 8.5/8.5p1 KexAlgorithms Support

libraries/ssh_crypto.rb
AlmaLinux has gained popularity being a "1:1 binary compatible with RHEL® and pre-Stream CentOS"
Adding support for AlmaLinux in ssh-baseline to make sure best settings are used.
Fixes #200
=> Add support for AlmaLinux

Rakefile, controls/ssh_spec.rb, controls/sshd_spec.rb, inspec.yml
In the last versions of Inspec and cinc-auditor, attribute is deprecated and input should be used.
https://docs.chef.io/workstation/cookstyle/inspec_deprecations_attributehelper/
=> use input instead of attribute

libraries/ssh_crypto.rb
This adds basic support for Ubuntu 22. I have not checked if there are newer (better) supported ciphers. I assume, the slightly older ones are still ok for a first update. Currently this control fails on Ubuntu 22 after hardening with our Ansible Collection is applied.
Signed-off-by: Martin Schurz <Martin.Schurz@t-systems.com>
=> add basic support for Ubuntu 22

libraries/ssh_crypto.rb
centos 7 and rocky linux announce their version with a major and minor number, like 8.1 or 8.4. centos stream however only uses the major number, e.g 8 or 9.
Signed-off-by: Sebastian Gumprich <sebastian.gumprich@t-systems.com>
=> fix detection for centos stream

libraries/ssh_crypto.rb
Signed-off-by: Sebastian Gumprich <sebastian.gumprich@t-systems.com>
=> simplify crypto library

controls/ssh_spec.rb, controls/sshd_spec.rb
we already had support vor MacOS (which is in part a BSD), now this is extended to FreeBSD and OpenBSD.
Testing is done in https://github.com/dev-sec/ansible-collection-hardening/pull/642
=> extend BSD Support
