- default/serverspec/ssh_spec.rb
See:
* https://github.com/TelekomLabs/chef-ssh-hardening/issues/66
* https://stribika.github.io/2015/01/04/secure-secure-shell.html
> reprioritize etm macs

- default/serverspec/ssh_spec.rb
References:
* https://stribika.github.io/2015/01/04/secure-secure-shell.html
* https://github.com/TelekomLabs/chef-ssh-hardening/issues/64
> remove sha1-based key-exchange mechanisms

- default/serverspec/ssh_spec.rb
> feature: debian 8 support

- playbooks/default.yml
This change adds more tests to check for different variable uses.
> Improve Ansible tests

- .travis.yml
- Gemfile
- Rakefile
- controls/ssh_spec.rb
- controls/sshd_spec.rb
- libraries/ssh_crypto.rb
Kudos @atomic111 for this contribution, see https://github.com/dev-sec/tests-ssh-hardening/pull/68/files
> update Gemfile and remove ruby 1.9.3 support

- .rubocop.yml
- LICENSE
- README.md
- Rakefile
- inspec.yml
- libraries/ssh_crypto.rb
- use new name in inspec.yml
- align repo versioning with inspec.yml
- update changelog task to use version from inspec.yml
> update profile metadata & tooling

- controls/sshd_spec.rb
as discussed in https://github.com/dev-sec/chef-ssh-hardening/issues/158
/cc @rndmh3ro @chris-rock maybe we need a change in ansible-ssh-hardening too (and puppet-ssh-hardening looks unmaintained :-( )
> Removal of DSA key

- controls/sshd_spec.rb
This is a test for https://github.com/dev-sec/chef-ssh-hardening/pull/163
Its a bit ugly compared to all other tests, I did not find another way, improvement ideas are welcome!
/cc @rndmh3ro @chris-rock maybe we need to have this change in ansible-ssh-hardening too?
> Test the strong DH primes

- libraries/ssh_crypto.rb
Related to the bugfix in train (used by inspec):
https://github.com/chef/train/commit/6b5d58250c7fd5d9f8e21ca7e27ca400ffed6b5a
> Add support for oracle

- controls/ssh_spec.rb
- controls/sshd_spec.rb
- libraries/ssh_crypto.rb
> Add openssh definitions for macos

- README.md
this is a permission test for @artem-sidorenko Do not merge
> update copyright name

- libraries/ssh_crypto.rb
this will fix #93 
Signed-off-by: Patrick Münch <patrick.muench1111@gmail.com>
> remove ripemd160 MAC from the macs66 list

- libraries/ssh_crypto.rb
Needed for dev-sec/ansible-ssh-hardening#164
> Initial support for Alpine Linux

- controls/sshd_spec.rb
> allow some customization of expected values depending on attributes

- libraries/ssh_crypto.rb
Current versions have newer OpenSSH
> Deprecated UsePrivilegeSeparation for Fedora/Amazon

- controls/ssh_spec.rb
- controls/sshd_spec.rb
- libraries/ssh_crypto.rb
starting from openssh 7.4 (rhel 7)
Fixes #95
> UseLogin is deprecated

- controls/sshd_spec.rb
Rename default to value (default is deprecated)
> Fix deprecations

- libraries/ssh_crypto.rb
Signed-off-by: Artem Sidorenko <artem.sidorenko@t-systems.com>
> Support of CentOS 8

- libraries/ssh_crypto.rb
Add recent ubuntu versions to get the correct algorithms list.
> ubuntu versions

- .github/workflows/release.yml
Signed-off-by: Michée Lengronne <michee.lengronne@coppint.com>
> API rate limiter debug

- CHANGELOG.md
Align versions in the changelog, the releases, the tags and inspec.yml
> Align versions everywhere in the project

- libraries/ssh_crypto.rb
These tweaks add support for Archlinux. Arch tracks the latest OpenSSH releases and my edits reflect this.
> Add support for Archlinux

- controls/sshd_spec.rb
Signed-off-by: Martin Schurz <Martin.Schurz@t-systems.com>
> reduce max startups in accordance with current cis benchmark

- controls/sshd_spec.rb
changed "Disable IgnoreRhosts" to "Enable IgnoreRhosts" to make the title match the control.
> Change "Disable IgnoreRhosts" to "Enable IgnoreRhosts"

- controls/sshd_spec.rb
RSA Host Keys smaller than 4096 bits are problematic
> add control for small RSA HostKey

- .rubocop.yml
- Rakefile
- controls/ssh_spec.rb
- controls/sshd_spec.rb
- libraries/ssh_crypto.rb
Signed-off-by: Martin Schurz <Martin.Schurz@t-systems.com>
> update code to conform to new linting rules

- libraries/ssh_crypto.rb
checked against current sshd_config of debian 11
Signed-off-by: Sebastian Gumprich <sebastian.gumprich@t-systems.com>
> add more support for debian 11

- .github/workflows/test.yml
- libraries/ssh_crypto.rb
Signed-off-by: Sebastian Gumprich <sebastian.gumprich@t-systems.com>
> add support for EL9
